### ISSUE TITLE
não sei o que fazer ou como começar

### ISSUE THREAD

**Issue by VictorVasconcelos2001** [ifpb-sr/zagua#10]
O que faço? e como faço as coisas do projeto?

**Comment by edusantana** [comment]
Bom dia @VictorVasconcelos2001 

Você ficou responsável por qual parte do projeto?

Segundo a ATA, na semana anterior você *faltou e não fez nada*. Com qual parte do projeto você está comprometido a realizar?

Hoje você me falou presencialmente que era "Backend e iria trabalhar no cadastro de Ponto de abastecimento", ok?

Então recomendo trabalhar junto com @milleidy ver #19 e a [feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/ponto_de_abastecimento.feature).

Você precisará:

- definir rotas (routes) para o Frontend para cada ação da feature
- definir o model de PontoDeAbastecimento, incluindo seus atributos.
- criar as migrations que alteram o banco de dados
- Implementar as funções da view com as implementações das regras de negócio.
