### ISSUE TITLE
não sei o que vou fazer

### ISSUE THREAD

**Issue by richardaraujo19** [ifpb-sr/zagua#12]

**Comment by edusantana** [comment]
Olá @richardaraujo19 você não sabe *o que* fazer ou *como fazer*?

Segundo a ATA você tinha *Estudando para fazer o banco*. Eu vou fazer um vídeo mostrando como faz isso. 

Mas até lá você pode ver ao vídeo [5a Introdução ao uso de banco de dados com o Flask e SQLAlchemy (iniciante)](https://www.youtube.com/watch?v=Cjj5fw3bwFY&list=PLTnAY6TvPRKIsiKuZ3p9NXRSheYLfopEO&index=10&t=0s).

**Comment by edusantana** [comment]
Mas você ficou responsável por implementar qual funcionalidade do backend?

Você pode ver em #10 as instruções que forneci a victor. Para você seriam as mesmas instruções, porém adaptadas para a funcionalidade que você ficou de implementar.

Qual a feature você ficou de implementar?
