### ISSUE TITLE
Como criar a pagina em html do cadastro do  comerciante 

### ISSUE THREAD

**Issue by querenhapuque** [ifpb-sr/zagua#13]

**Comment by edusantana** [comment]
Para realização do trabalho de Frontend, criação de páginas e templates, assistir aos vídeos dos capítulos 3 e 4 é muito útil. Veja a playlist:

- https://www.youtube.com/playlist?list=PLTnAY6TvPRKIsiKuZ3p9NXRSheYLfopEO

Em breve vou fazer outro vídeo específico demonstrando novamente utilizando os códigos do projeto.

**Comment by edusantana** [comment]
Primeiro, qual foi a feature que você ficou de realizar?

1. [features/comerciante/loja.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/loja.feature)
2. [features/comerciante/ponto_de_abastecimento.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/ponto_de_abastecimento.feature)
3. [features/comerciante/credito_venda_trasacao_presencial.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/credito_venda_trasacao_presencial.feature)
4. [features/comerciante/credito_venda_trasacao_bancaria.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/credito_venda_trasacao_bancaria.feature)
5. [features/comerciante/ponto_de_abastecimento.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/ponto_de_abastecimento.feature)
6. [features/comerciante/autoservico.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/autoservico.feature)
7. [features/comerciante/credito_venda_trasacao_bancaria.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/credito_venda_trasacao_bancaria.feature)
8. [features/comerciante/credito_venda_trasacao_presencial.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/credito_venda_trasacao_presencial.feature)
9. [features/usuario_cadastro.feature](https://github.com/ifpb-sr/zagua/blob/master/features/usuario_cadastro.feature)

Não existe a feature "cadastro de comerciante". Existe cadastro de usuário. Quando um usuário tiver uma loja ele será considerado um Comerciante. Atualmente a criação de um loja é realizado diretamente no banco de dados, sem precisar de uma tela para cadastrar a loja.

**Comment by querenhapuque** [comment]
Professor a minha parte junto com a das meninas era de manter online a
loja, era algo assim, tinha outras funções tbm, mas obg por lembrar

Em ter, 27 de ago de 2019 09:19, Eduardo de Santana Medeiros Alexandre <
notifications@github.com> escreveu:
