### ISSUE TITLE
Não sei por onde e como começar

### ISSUE THREAD

**Issue by milenxxaa** [ifpb-sr/zagua#14]
Não sei oq fazer e como fazer nem por onde fazer  #?}?????????????

**Comment by querenhapuque** [comment]
Fazer o que?

**Comment by edusantana** [comment]
@milenxxaa na ATA ficou registrado que você estava trabalhando com Stefanny e Lucas **desenhando o modelo de Cadastro de revendedor**.

Todas as funcionalidades de Revendedor não são mais prioridades. Lembro que vocês passaram a implementar outra coisa. Qual era a coisa?

Independente do que seja feito, para realização do trabalho de Frontend, criação de páginas e templates, assistir aos [vídeos dos capítulos 3 e 4 é muito útil](https://www.youtube.com/playlist?list=PLTnAY6TvPRKIsiKuZ3p9NXRSheYLfopEO).

Em breve vou fazer outro vídeo específico demonstrando novamente utilizando os códigos do projeto.

**Comment by edusantana** [comment]
Você ficou com qual dessas funcionalidades?

1. [features/comerciante/loja.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/loja.feature)
2. [features/comerciante/ponto_de_abastecimento.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/ponto_de_abastecimento.feature)
3. [features/comerciante/credito_venda_trasacao_presencial.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/credito_venda_trasacao_presencial.feature)
4. [features/comerciante/credito_venda_trasacao_bancaria.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/credito_venda_trasacao_bancaria.feature)
5. [features/comerciante/ponto_de_abastecimento.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/ponto_de_abastecimento.feature)
6. [features/comerciante/autoservico.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/autoservico.feature)
7. [features/comerciante/credito_venda_trasacao_bancaria.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/credito_venda_trasacao_bancaria.feature)
8. [features/comerciante/credito_venda_trasacao_presencial.feature](https://github.com/ifpb-sr/zagua/blob/master/features/comerciante/credito_venda_trasacao_presencial.feature)
9. [features/usuario_cadastro.feature](https://github.com/ifpb-sr/zagua/blob/master/features/usuario_cadastro.feature)
