### ISSUE TITLE
como instalar o pipenv

### ISSUE THREAD

**Issue by VictorVasconcelos2001** [ifpb-sr/zagua#15]
não consigo instalar pois esta falando que o comando não foi encontrado!!

**Comment by VictorVasconcelos2001** [comment]
Para instalar o pipenv no AWS:

```
python3 -m pip install pipenv --user
```

**Comment by edusantana** [comment]
Caso sua dúvida persistir favor reabrir o issue com sua dúvida, por enquanto estou fechando ela.
