### ISSUE TITLE
Quantas telas serão necessárias para cadastrar os pontos de abastecimento?

### ISSUE THREAD

**Issue by milleidy** [ifpb-sr/zagua#19]
Quantas telas serão necessárias para cadastrar os pontos de abastecimento?

**Comment by edusantana** [comment]
Eu suponho:

- [Tela de criar novo abastecimento](https://github.com/ifpb-sr/zagua/blob/31f7315e8789623a81e003ef92db092d12400a8d/features/comerciante/ponto_de_abastecimento.feature#L21-L36)
- [Tela de edição do ponto de abastecimento](https://github.com/ifpb-sr/zagua/blob/31f7315e8789623a81e003ef92db092d12400a8d/features/comerciante/ponto_de_abastecimento.feature#L38-L54) (você vai ter que essa tela é muito parecida com a anterior)
- [Tela para exibir as informações dos pontos de abastecimento](https://github.com/ifpb-sr/zagua/blob/31f7315e8789623a81e003ef92db092d12400a8d/features/comerciante/ponto_de_abastecimento.feature#L71-L76)
- [A tela de apagar](https://github.com/ifpb-sr/zagua/blob/31f7315e8789623a81e003ef92db092d12400a8d/features/comerciante/ponto_de_abastecimento.feature#L56-L69) pode ser utilizada junto com a anterior (basta adicionar um botão para cada ponto de abastecimento que deseja-se apagar)
