### ISSUE TITLE
Como faço para começar a programar um banco  de dados? 

### ISSUE THREAD

**Issue by raymayara** [ifpb-sr/zagua#20]

**Comment by edusantana** [comment]
@raymayara 

Você ficou com a funcionalidade de cadastrar usuário: [features/usuario_cadastro.feature](https://github.com/ifpb-sr/zagua/blob/master/features/usuario_cadastro.feature)


Você precisará:

- definir rotas (routes) para o Frontend para cada ação da feature
- definir o model de User ou Usuário, incluindo seus atributos (nome, telefone, email etc)
- criar as migrations (que alteram o banco de dados)
- Implementar as funções da view com as implementações das regras de negócio (incluir usuário, autenticar etc)

**Comment by edusantana** [comment]
Essa resposta tirou sua dúvida, ou ainda permanece a dúvidas? Se ainda estiver com dúvida, por gentileza, expresse novamente qual sua dúvida.
