### ISSUE TITLE
como criar um relacionamento entre usuario e loja, colocando o comerciante como dono? 

### ISSUE THREAD

**Issue by raymayara** [ifpb-sr/zagua#25]

**Comment by edusantana** [comment]
Apaga essa linha: https://github.com/ifpb-sr/zagua/blob/bebf024dac95163369bbe938488a7847c56daff0/zagua/models.py#L12

Modifica essa linha: 

https://github.com/ifpb-sr/zagua/blob/bebf024dac95163369bbe938488a7847c56daff0/zagua/models.py#L21

Para:

```python
dono_id = db.Column(db.Integer, db.ForeignKey('Usuario.id'))
```
