### ISSUE TITLE
Qual comando eu uso para ativar/criar meu banco de dados

### ISSUE THREAD

**Issue by richardaraujo19** [ifpb-sr/zagua#37]

**Comment by raymayara** [comment]
Também tenho essa dúvida :+1:

**Comment by richardaraujo19** [comment]
( •_•) 
( ง )ง
 /︶\ 
Vem tranquilo professor

**Comment by edusantana** [comment]
No [diskbode](https://github.com/edusantana/disk-bode/blob/master/README.md), isso é realizado através das seguintes instruções no README:

> Agora vamos adicionar valores ao banco de dados:

>       flask shell

> Depois, insere os seguintes valores:

```python
from app import db, ProdutoTipo
db.create_all()
```
