### ISSUE TITLE
Nao sei fazer

### ISSUE THREAD

**Issue by RayssaLohanny** [ifpb-sr/zagua#38]
Como executar o código de criação de formulários  
No qual no formulário o cliente vai solicitar e selecionar o volume de água desejado, e de qual ponto ele quer.
Como ver se o código de criação do formulário está pegando ?

**Comment by edusantana** [comment]
Bom dia @RayssaLohanny 

Quando você pergunta dessa forma eu penso que você está me perguntando a resposta do que você deseja realizar.

Eu vou pensar em como responder isso sem lhe dá a resposta do que você deve realizar.

Por enquanto, pode começar assistindo ao vídeo do capítulo 3. Você já assistiu?
