### ISSUE TITLE
Duvida com estilização com as paginas em Django

### ISSUE THREAD

**Issue by Williais** [ifpb-sr/zagua#54]
como alterar estilo do Body de acordo com a pagina?

e como eu poderia adicionar um arquivo JS para fazer animação e fazer os links

**Comment by alefemoreira** [comment]
# Como alterar estilo do Body de acordo com a pagina?
Observe que no base.html te um bloco no head chamado head_file

https://github.com/ifpb-sr/zagua/blob/85d7088d9d94ae179b24ed931c7062f0fdd42a62/zagua/templates/base.html#L10

Ele serve para ser substituído pelos arquivos filhos dele como o arquivo [login.hml](https://github.com/ifpb-sr/zagua/blob/master/zagua/templates/login/login.html). Observe que, nas linhas 6 e 7 e 8, ele tem um bloco desse, mas que nele tem algo escrito

```jinja
6 {% block head_files %}
7     <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='login.css') }}" />
8 {% endblock %}
```
Então, sempre que você quiser colocar um CSS ou JS exclusivo para uma página, basta colocar a tag de inseri-los entre esses blocos.

Ainda assim, você precisa tomar cuidado no código css. Pode ocorrer de ter uma regra de style para ele padrão do bootstrap ou até mesmo outro css que você mesmo pode ter criado. Para isso use sempre o `!important` nas regras que deve sobrepostas a outras, como por exemplo:

https://github.com/ifpb-sr/zagua/blob/85d7088d9d94ae179b24ed931c7062f0fdd42a62/zagua/static/login.css#L2

Além disso sempre se atente a ordem de prioridade(precedência) das regras de style:

1. inline
2. ID
3. Classe
4. elemento

# como eu poderia adicionar um arquivo JS para fazer animação e fazer os links

Bem, se adiciona um arquivo JS do msm modo que se adiciona um arquivo CSS.
Veja a issue #52 . 
Não entendi o que vc quis dizer com o "fazer os links", seria linkar o arquivo com o html? responda nos comentários.

**Comment by Williais** [comment]
oq vc quis dizer com "sempre se atente a ordem de prioridade(precedência) das regras de style"?

**Comment by edusantana** [comment]
@alefemoreira para repetir o que a outra pessoa escreveu utilize a [formatação de quote](https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-text) em markdown com o simbolo `>`

@Williais estamos estudando Flask. [Django](https://www.djangoproject.com) é outra coisa.

**Comment by Williais** [comment]
@edusantana tudo bem, professor
obrigado
