### ISSUE TITLE
arquivo JS no proprio index ou separado

### ISSUE THREAD

**Issue by Williais** [ifpb-sr/zagua#55]
estou com uma duvida

preciso ter no meu codigo um arquivo js

mas queria saber se eu posso colocar o meu script no bloco {% block script %}{% endblock %} ou eu faço um arquivo.js e linko no base.html?

**Comment by edusantana** [comment]
Coloca o js na pasta static e linka no base.

**Comment by Williais** [comment]
o link seria assim: <link rel="JavaScript" type="text/js" href="{{ url_for('static', filename='nome_projeto'}}"/> ???????????

**Comment by Williais** [comment]
<link rel="javascript" type="text/js" href="{{ url_for('static', filename='nome.js') }}"/>
