### ISSUE TITLE
como criar um banco de dados?

### ISSUE THREAD

**Issue by raymayara** [ifpb-sr/zagua#9]

**Comment by XdWalker** [comment]
Eu tenho a mesma dúvida.

**Comment by edusantana** [comment]
Recomendo assistir ao vídeo [5a Introdução ao uso de banco de dados com o Flask e SQLAlchemy (iniciante)](https://www.youtube.com/watch?v=Cjj5fw3bwFY&list=PLTnAY6TvPRKIsiKuZ3p9NXRSheYLfopEO&index=10&t=0s).

Quanto mais detalhe fornecer na dúvida melhor, pois poderei responder mais profundamente. Vou preparar outro vídeo depois.

**Comment by richardaraujo19** [comment]
Estou assistindo video e fazendo isso com Rayane
